[project]
name = "my-uv-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Egor Smetanin", email = "smetanine26@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "colorama>=0.4.6",
    "httpx>=0.28.1",
    "markdown>=3.11",
    "pyfiglet>=1.0.4",
    "requests>=2.34.2",
    "rich>=15.0.0",
    "tabulate>=0.10.0",
    "tqdm>=4.70.1",
]

[project.scripts]
my-uv-app = "my_uv_app:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
